# Generated by Django 5.0.6 on 2026-09-01 12:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="ragione sociale"),
                ),
                (
                    "vat",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9]{8,20}$", "Partita IVA non valida"
                            )
                        ],
                        verbose_name="partita IVA",
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Gruppo Telegram in cui vengono recapitati i report PDF.",
                        null=True,
                        verbose_name="chat ID gruppo aziendale",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("FREE", "Freemium"),
                            ("PRO", "Pro"),
                            ("AGENCY", "Agency White-Label"),
                        ],
                        default="FREE",
                        max_length=10,
                    ),
                ),
                ("brand_name", models.CharField(blank=True, max_length=120)),
                (
                    "brand_logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "brand_color",
                    models.CharField(blank=True, default="#0B6BCB", max_length=7),
                ),
                ("custom_domain", models.CharField(blank=True, max_length=255)),
                (
                    "rspp_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome riportato in calce al report per la firma.",
                        max_length=200,
                        verbose_name="RSPP di riferimento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "azienda",
                "verbose_name_plural": "aziende",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(db_index=True, unique=True)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("first_name", models.CharField(blank=True, max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                (
                    "language_code",
                    models.CharField(blank=True, default="it", max_length=8),
                ),
                ("photo_url", models.URLField(blank=True)),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OPERATOR", "Operatore"),
                            ("RSPP", "RSPP / Consulente"),
                            ("ADMIN", "Amministratore azienda"),
                        ],
                        default="OPERATOR",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "utente Telegram",
                "verbose_name_plural": "utenti Telegram",
                "ordering": ["-date_joined"],
            },
        ),
    ]
