# Generated by Django 5.0.6 on 2026-09-01 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LIFT", "Sollevamento"),
                            ("PC", "Videoterminale"),
                            ("HANDLING", "Movimentazione"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "worker_ref",
                    models.CharField(
                        blank=True,
                        help_text="Codice pseudonimo (es. MAG-014). Non inserire dati identificativi.",
                        max_length=64,
                        verbose_name="riferimento lavoratore",
                    ),
                ),
                (
                    "workstation",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="postazione"
                    ),
                ),
                ("pose_data", models.JSONField(default=dict)),
                ("task_data", models.JSONField(blank=True, default=dict)),
                (
                    "risk_score",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("GREEN", "Accettabile"),
                            ("YELLOW", "Attenzione"),
                            ("ORANGE", "Rischio elevato"),
                            ("RED", "Rischio inaccettabile"),
                        ],
                        default="GREEN",
                        max_length=6,
                    ),
                ),
                ("lifting_index", models.FloatField(blank=True, null=True)),
                ("recommended_weight_limit", models.FloatField(blank=True, null=True)),
                ("light_lux", models.FloatField(blank=True, null=True)),
                ("noise_db", models.FloatField(blank=True, null=True)),
                ("device_tilt_deg", models.FloatField(blank=True, null=True)),
                ("findings", models.JSONField(blank=True, default=list)),
                ("duration_s", models.FloatField(default=0)),
                ("frames_analyzed", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "In attesa"),
                            ("PROCESSING", "Elaborazione report"),
                            ("READY", "Report pronto"),
                            ("FAILED", "Errore"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "pdf_report",
                    models.FileField(blank=True, null=True, upload_to="reports/%Y/%m/"),
                ),
                ("report_error", models.TextField(blank=True)),
                (
                    "delivered_to_telegram_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "valutazione",
                "verbose_name_plural": "valutazioni",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField()),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                ("ok", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["company", "-created_at"], name="assessments_company_f818bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["company", "type", "-created_at"],
                name="assessments_company_087aa7_idx",
            ),
        ),
    ]
