# Generated by Django 5.1.4 on 2026-09-01 20:59

import django.core.validators
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "profile_id",
                    models.CharField(
                        default=profiles.models.generate_profile_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "telegram_user_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "chest_cm",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(20.0),
                            django.core.validators.MaxValueValidator(300.0),
                        ]
                    ),
                ),
                (
                    "waist_cm",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(20.0),
                            django.core.validators.MaxValueValidator(300.0),
                        ]
                    ),
                ),
                (
                    "hips_cm",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(20.0),
                            django.core.validators.MaxValueValidator(300.0),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
