# Generated by Django 5.1.4 on 2026-09-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="style_advice",
            field=models.TextField(blank=True, null=True),
        ),
    ]
